match 'doc_pu', :controller => 'doc_pu', :action => 'index', :via => :get
match 'doc_pu/new', :controller => 'doc_pu', :action => 'new', :via => [:get, :post]
match 'doc_pu/edit', :controller => 'doc_pu', :action => 'edit', :via => [:get, :post, :patch]
match 'doc_pu/open', :controller => 'doc_pu', :action => 'open', :via => [:get, :post]
match 'doc_pu/build', :controller => 'doc_pu', :action => 'build', :via => [:get, :post]
match 'doc_pu/build_remote', :controller => 'doc_pu', :action => 'build_remote', :via => [:get, :post]
match 'doc_pu/clean', :controller => 'doc_pu', :action => 'clean', :via => [:get, :post]
match 'doc_pu/clean_remote', :controller => 'doc_pu', :action => 'clean_remote', :via => [:get, :post]
match 'doc_pu/code', :controller => 'doc_pu', :action => 'code', :via => [:get]
match 'doc_pu/delete', :controller => 'doc_pu', :action => 'delete', :via => [:get, :post]
match 'doc_pu/template', :controller => 'doc_pu', :action => 'template', :via => [:get, :post]

match 'doc_pu_wiki', :controller => 'doc_pu_wiki', :action => 'index', :via => [:get]
match 'doc_pu_wiki/new', :controller => 'doc_pu_wiki', :action => 'new', :via => [:get, :post]
match 'doc_pu_wiki/edit', :controller => 'doc_pu_wiki', :action => 'edit', :via => [:get, :post, :patch]
match 'doc_pu_wiki/delete', :controller => 'doc_pu_wiki', :action => 'delete', :via => [:get, :post]
match 'doc_pu_wiki/edit_order', :controller => 'doc_pu_wiki', :action => 'edit_order', :via => [:get, :post]

match 'doc_pu_settings/test_latex', :controller => 'doc_pu_settings', :action => 'test_latex', :via => [:post]
match 'doc_pu_settings/test_makeindex', :controller => 'doc_pu_settings', :action => 'test_makeindex', :via => [:post]
match 'doc_pu_settings/test_template', :controller => 'doc_pu_settings', :action => 'test_template', :via => [:post]
